### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by yoX64** [yoX64/dia-api#18]
Please make sure we have a system that will deploy at every push/merge in master. Also, this would mean that we will have a public IP/domain that will be accessible for the developers.

**Comment by yoX64** [comment]
@bucatzel asta e gata, nu? cred ca il putem inchide

**Comment by bucatzel** [comment]
not yet, inca nu se ruleaza automagic.

**Comment by yoX64** [comment]
oki doki
